<a href="https://colab.research.google.com/github/nds-najam/PyTorch_Tutorial/blob/master/research/Lecture_5_1_pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Simple Linear Model

In [3]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [4]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.4000],
        [0.3977],
        [0.4269],
        [0.3961],
        [0.3566],
        [0.3518],
        [0.4390],
        [0.4086],
        [0.4133],
        [0.4200]], grad_fn=<SigmoidBackward0>)

In [9]:
features

tensor([[0.0764, 0.6529, 0.5295, 0.0953, 0.1886],
        [0.4569, 0.3242, 0.7248, 0.4546, 0.4002],
        [0.7485, 0.3460, 0.5967, 0.0481, 0.6713],
        [0.1232, 0.3457, 0.4081, 0.1877, 0.4325],
        [0.8974, 0.9676, 0.9397, 0.7794, 0.7747],
        [0.1877, 0.7891, 0.2845, 0.2309, 0.9288],
        [0.6996, 0.4469, 0.3235, 0.2787, 0.4837],
        [0.5964, 0.8615, 0.3500, 0.2124, 0.5942],
        [0.8030, 0.6978, 0.3641, 0.4388, 0.6740],
        [0.8070, 0.2439, 0.7153, 0.5807, 0.4609]])

In [5]:
model.linear.weight

Parameter containing:
tensor([[ 0.3594, -0.1369, -0.2300, -0.2043, -0.3454]], requires_grad=True)

In [6]:
model.linear.bias

Parameter containing:
tensor([-0.1372], requires_grad=True)

In [7]:
!pip install torchinfo

In [8]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

NN with Hidden Layer

In [10]:
# create model class
# Create a NN model with 5 inputs, 1 hidden layer with 3 nodes
#
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [11]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.4507],
        [0.4193],
        [0.4469],
        [0.4154],
        [0.4404],
        [0.4143],
        [0.3855],
        [0.4508],
        [0.4282],
        [0.4395]], grad_fn=<SigmoidBackward0>)

In [12]:
print(model.linear1.weight)
print(model.linear1.bias)
print(model.linear2.weight)
print(model.linear2.bias)
print(model.parameters)

Parameter containing:
tensor([[ 0.1862,  0.3777,  0.3692,  0.3071,  0.0604],
        [-0.4075, -0.0662, -0.1950,  0.0276, -0.2489],
        [ 0.4023,  0.1987, -0.1756,  0.2191,  0.4322]], requires_grad=True)
Parameter containing:
tensor([ 0.2111, -0.0322,  0.2282], requires_grad=True)
Parameter containing:
tensor([[-0.1620, -0.2974,  0.5559]], requires_grad=True)
Parameter containing:
tensor([-0.5500], requires_grad=True)
<bound method Module.parameters of Model(
  (linear1): Linear(in_features=5, out_features=3, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=3, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)>


In [13]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

NN model with a single hidden layer using a Sequential Containser

In [14]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [15]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.6200],
        [0.6300],
        [0.5891],
        [0.6160],
        [0.6312],
        [0.6323],
        [0.6045],
        [0.6077],
        [0.6276],
        [0.6311]], grad_fn=<SigmoidBackward0>)

In [ ]:
# show model weights
model.linear2.weight

Parameter containing:
tensor([[0.5021, 0.5738, 0.4083]], requires_grad=True)